### PR TITLE
Add multisig testnet matching

### PR DESCRIPTION
**Pull request by humanumbrella**
small bugfix

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks for the PR! Do you have any documentation you can link to on why `m/45'/1...` is testnet? I'm not familiar with that and don't see it in the [the BIP45 spec](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki). The examples in the spec even include some `m/45'/1...` that I believe are mainnet (they're not explicitly testnet).

I checked Electrum and Sparrow and they both default to `m/45'/0` (not `m/45'/1`), but you can alter them.

Note that if you're trying to import a `Named{HD}PublicKey` (perhaps as part of a PSBT) you can set the network (this code is only called when no network is supplied). Perhaps that's the logic you're looking for?

**Comment by humanumbrella** [comment]
Unfortunately, I don't have a reference to a BIP or spec as we use a combination of them, hehe. 

One way to think of Unchained's usage pattern is essentially `BIP44` except under `m/45'` instead of `m/44'` to both designate it's multisig and to avoid any `BIP44` space usage collisions that may be used for singlesig. Here's a link to [trezor firmware carveouts](https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/bitcoin/keychain.py#L80-L87) that may provide some additional clarity.

You're right that `m/45'/1` could be mainnet per the spec - but this PR adds `m/45'/1'/*` as testnet, which is *not* specified in the spec. Interestingly that would still not cover all of our use cases, so perhaps I do need to go find the other logic you reference.

What do you think?

**Comment by mflaxman** [comment]
Gotcha... Can you try passing in the network to the `Named{HD}PublicKey` constructor?

**Comment by humanumbrella** [comment]
Going to close this, as I think this is user error. Will reopen if I determine otherwise, ty for the responses.

**Pull request closed without merging**
