### PR TITLE
refactored compact filters

### PR DESCRIPTION
**Pull request by jimmysong**
Put compact filter stuff into its own file and added a CompactFilter class. The idea is that you can quickly check a Script against the filter. Probably could use a way to check an address or even an HD key against it.

### CODE REVIEW

**Comment by mflaxman** [comment]
Awesome! Will review tomorrow.

**Review by mflaxman — APPROVED** [review]
LGTM, nice!

Getting that out of the helpers file is much cleaner. Do you want to bump the version in `setup.py` for a pip release? Not necessary but easy for me (or you I think) to run the `update_pypi.sh` script.

**Comment by jimmysong** [comment]
I bumped the version, but something is up with the 3.9 environment and black. The other python versions seem to be passing the black stuff fine, but not 3.9. @mflaxman

**Comment by mflaxman** [comment]
@jimmysong this should resolve the issue: https://github.com/buidl-bitcoin/buidl-python/pull/96

**Comment by mflaxman** [comment]
@jimmysong you have merge access, right? I'm assuming you just forgot to merge this in. Merging now.

**Comment by mflaxman** [comment]
`2.2.9` is now live on pypi btw https://pypi.org/project/buidl/0.2.29/

**Pull request merged**
