### PR TITLE
Added Compact Filters/Neutrino stuff

### PR DESCRIPTION
**Pull request by jimmysong**
These should allow you to verify using compact filters instead of merkle proofs

### CODE REVIEW

**Comment by mflaxman** [comment]
Cool, I've been wanting a good library for compact block filters!

How about [this library](https://github.com/majek/pysiphash) for pure python siphash24 (no dependencies)? Could work the same as `cecc.py`/`pecc.py`.

Do you like [black](https://pypi.org/project/black/)? I think it's awesome but the PR is failing the checks (just run `$ black .` and it will fix it for you.

**Comment by jimmysong** [comment]
i'm fine with switching. black should no longer fail, it's the csiphash issue from what i can tell?

**Comment by mflaxman** [comment]
`black` is failing on a ton of (other) stuff:
https://github.com/buidl-bitcoin/buidl-python/pull/4/checks?check_run_id=1299114429

```
Oh no! 💥 💔 💥
7 files would be reformatted, 27 files would be left unchanged.
```

If you just run `$ black .` on your branch it should fix that easily.

**Comment by mflaxman** [comment]
I just submitted this PR (https://github.com/buidl-bitcoin/buidl-python/pull/5) to your branch, if you agree + merge it will make your tests pass so yours can merge all this in!

**Comment by mflaxman** [comment]
Any reason you didn't merge this into main? It LGTM!

**Pull request merged**
