### PR TITLE
add testnet flag to psbt

### LINKED ISSUE #13: PSBT.parse() always thinks PSBT's TX obj is mainnet
Example:
```
from buidl.psbt import PSBT

PSBT_B64 = "cHNidP8BAH0CAAAAAfsWeOlaFJKfqlQHzx+WgjRJlEB9XLzMCXchCw4si7PDAQAAAAD/////AoUIAAAAAAAAIgAgxb6HvJsx6G8mjBf/ERAtVkJHNNu5n0t6JaZr54V3Og7WHQAAAAAAABYAFMINV2dNtzP+jUjqf2bIwsPrqp+7AAAAAAABASsQJwAAAAAAACIAIDuuQfOewCl82IjzKJAjQy5pUQKaE7HBtEJA5pYh/y54AQWLUSECOLBbCCUjX61VtXIa9P1ZPhpsz0okfHLI8lQM/2dlnQshA1gkYwW4I1IawxzVo8L53yV1y/R7Jq3aeypId5KPdevNIQOv86ZXTRchmJ8w5IXJ9Vx18yQxUytq3xkZdCBKn4vTgiEDsT5favW6RBtmK7GQJ3HBl3p4AXDoJU6HAYrl9XXna/1UriIGAjiwWwglI1+tVbVyGvT9WT4abM9KJHxyyPJUDP9nZZ0LHBKYDu0wAACAAQAAgAAAAIACAACAAAAAAAcAAAAiBgNYJGMFuCNSGsMc1aPC+d8ldcv0eyat2nsqSHeSj3XrzRz30ECQMAAAgAEAAIAAAACAAgAAgAAAAAAHAAAAIgYDr/OmV00XIZifMOSFyfVcdfMkMVMrat8ZGXQgSp+L04Icx9BkijAAAIABAACAAAAAgAIAAIAAAAAABwAAACIGA7E+X2r1ukQbZiuxkCdxwZd6eAFw6CVOhwGK5fV152v9HDpStc0wAACAAQAAgAAAAIACAACAAAAAAAcAAAAAAQGLUSECPVlulR9WOiDFRX7p3cyIGDbmMn0qBJA0WHIRc6PWFlwhAskkzwGB+E7aT3ibDWIVgqmC1VprCHUq4OMVlzKJTZAdIQLfBhkEe8XmHQSm0vTSu2XZEQu58w9z4cBm7pzF5HC0gCED00gxYCXN/UhH6szbR+Ydq5+gxZN45Am/ruggbkUuSLRUriICAj1ZbpUfVjogxUV+6d3MiBg25jJ9KgSQNFhyEXOj1hZcHPfQQJAwAACAAQAAgAAAAIACAACAAQAAAAIAAAAiAgLJJM8BgfhO2k94mw1iFYKpgtVaawh1KuDjFZcyiU2QHRw6UrXNMAAAgAEAAIAAAACAAgAAgAEAAAACAAAAIgIC3wYZBHvF5h0EptL00rtl2RELufMPc+HAZu6cxeRwtIAcEpgO7TAAAIABAACAAAAAgAIAAIABAAAAAgAAACICA9NIMWAlzf1IR+rM20fmHaufoMWTeOQJv67oIG5FLki0HMfQZIowAACAAQAAgAAAAIACAACAAQAAAAIAAAAAAA=="

psbt_obj = PSBT.parse_base64(PSBT_B64)
print(psbt_obj.tx_obj.testnet)  # returns False but should be True
```

Screen Shot 2020-11-01 at 12 45 17 PM

### PR DESCRIPTION
**Pull request by jimmysong**
This fixes #13

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @jimmysong!

I like the `path_is_testnet` helper, but it's only 99.9% accurate as a heuristic. What would you think about instead adding a `testnet` boolean argument to the `PSBT.parse*()` methods?

Then a developer would write:
```
psbt_obj = PSBT.parse_base64(PSBT_B64, testnet=path_is_testnet(root_path))
```

Obviously, a better solution would be for PSBT to have a testnet flag, but that's a separate issue.

**Comment by jimmysong** [comment]
That wouldn't work because the root path is inside the PSBT text. You'd have to parse it twice, once to grab the root paths and then a second time to pass in the testnet variable.

**Comment by mflaxman** [comment]
Ah, that is tricky.

My concern is just to have a default that isn't 100% correct, even if it's right > 99.9%. It could lead to some crazy hard to figure out edge cases.

How about keeping everything you've got but also adding a `testnet` boolean argument to the `PSBT.parse*()` methods? That way if you know the desired network you can explicitly set it when parsing, but if it's `None` then the nice `path_is_testnet()` logic you wrote kicks in.

Of course the best would be to have this in the PSBT spec, but that's a much bigger topic in #13 .

**Comment by jimmysong** [comment]
fixed

**Comment by mflaxman** [comment]
Awesome! Any reason you didn't add `testnet` to `parse_base64()`? I was thinking I'd add that in.

**Comment by jimmysong** [comment]
just forgot. please feel free to modify.

**Pull request merged**
