### PR TITLE
add missing import, improve shamir testing in multiwallet

### PR DESCRIPTION
**Pull request by mflaxman**
Shamir testing now does the following:
* Defaults to testing all permutations. Call me crazy, but if you're going through the headache of setting up a giant SSSS (8-of-16), you want to be sure that every combo works. I buried restrictions (with your old defaults) in the advanced section.
*When testing a subset, it randomizes which ones to test. Shouldn't matter, but I wanted to be extra sure.

### CODE REVIEW

**Review by jimmysong — APPROVED** [review]
Yep, looks fine. 8-of-16 is pretty hard-core =) BTW, I put in a PR for similar stuff to embit, which is upstream of Specter DIY

**Comment by mflaxman** [comment]
Sorry, after submitting the PR I realized I didn't like the added complexity of how I wrote it. Harder to maintain => greater likelihood the tests weren't working at all vs were only working on a working subset (while other combos didn't work).

I tweaked the UI/code so that it does very similar to the previous, but is now clearer to read. I don't randomize if advanced users choose to test a subset, that's their choice.

Still good to merge?

**Comment by mflaxman** [comment]
> Yep, looks fine. 8-of-16 is pretty hard-core =) BTW, I put in a PR for similar stuff to embit, which is upstream of Specter DIY

8-of-16 is less hardcore if you give more shares to some parties (like family) vs others. But ya, I prefer lower thresholds like 4-of-16 (and perhaps with 2 shares for family it's even better).

I think giving out more shares > groups, but haven't spent that much time thinking about it.

**Comment by jimmysong** [comment]
lgtm

**Pull request merged**
