### PR TITLE
CLI Multisig Hardware Wallet

### PR DESCRIPTION
**Pull request by mflaxman**
All in < 500 LOCs thanks to buidl being awesome.

See [readme](https://github.com/buidl-bitcoin/buidl-python/tree/psbt-signer/examples) for instructions.

@jimmysong, give it a shot?

### CODE REVIEW

**Comment by jimmysong** [comment]
I think using the `cmd` library would be perfect for this. It's really easy to use and gives a rudimentary CLI interface for everything instead of lots of hard-to-remember command-line arguments. I have an example of how it works here:

https://github.com/jimmysong/lepton/blob/testing/run.py

**Comment by mflaxman** [comment]
That is neat, kind of like a UX-builder for CLI apps.

That said, isn't this pretty straightforward?

```
$ python3 examples/psbt-signer.py -h
usage: psbt-signer.py [-h] --psbt-file PSBT_FILE --mnemonic MNEMONIC [--verbose] [--display-btc]

Sign a multisig transaction via PSBT.

optional arguments:
  -h, --help            show this help message and exit
  --psbt-file PSBT_FILE
                        Partially Signed Bitcoin Transaction (PSBT) file to sign. /path/to/file.psbt
  --mnemonic MNEMONIC   Full BIP39 mnemonic
  --verbose             Print out extra debugging info (experts only).
  --display-btc         Display BTC as units instead of satoshis


$ python3 examples/seedpicker.py -h
usage: seedpicker.py [-h] --firstWords FIRSTWORDS [--testnet] [--verbose]

Calculate checksum word and display multisig extended pubkey information for your seed phrase

optional arguments:
  -h, --help            show this help message and exit
  --firstWords FIRSTWORDS
                        First words of your seed phrase that you want to find the appropriate final (checksum) word to append
  --testnet             Generate extended pubkey info and BIP32 paths for testnet.
  --verbose             Print out extra debugging info (experts only).


$ python3 examples/verify-multisig-address.py -h
usage: verify-multisig-address.py [-h] --descriptor DESCRIPTOR [--limit LIMIT] [--offset OFFSET]

Derive bitcoin addresses from your multisig wallet public key information.

optional arguments:
  -h, --help            show this help message and exit
  --descriptor DESCRIPTOR
                        Bitcoin core script descriptor /path/to/file.json
  --limit LIMIT         The number of addresses you want to display (default is 20).
  --offset OFFSET       Start displaying addresses at this index number (default is 0).
```

I like that `cmd` doesn't add any external dependencies (main use-case should be airgapped, so dependencies are a PITA), but my main concern is that it's not as scriptable. You might be storing your seed phrase in a file (that you `cat`) or an environmental variable (that you `echo`), and you might be running this process regularly in your business operations.

That said, it'd be a pretty easy change. I just like how it's as simple as possible right now. If you want a UX, you probably want a GUI that hooks up to your webcam (could be the next project!) and not a CLI app in the first place.

**Comment by jimmysong** [comment]
I really hate bash scripting so I try to avoid it whenever possible, especially things with all manner of command-line arguments.
I think if you're scripting with this library, you're probably going to write the script in python.
Essentially, something that walks a reasonably astute person through what they need to do in a command-line interface is what I would like. That said, this might not be your goal.

**Comment by mflaxman** [comment]
@jimmysong check it out now, it's working via `cmd` and I got rid of the bash examples!

I put the `multiwallet.py` file in the root directory so someone could just download/clone this repo and everything would work (no dependencies needed, which is much easier for airgap operations).

Some of the UX things are really nice (no need to RTFM) and some are a little annoying as there are lots of prompts (but sensible defaults means many of them you can just hit enter on).

In the future I could add an advanced/hidden feature that allows you to pass in environmental variables:
```bash
$ BIP39_SEED="zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo abstract" python multiwallet.py
```

Send me some `tbtc` with this (`tb1q8whyruu7cq5hekyg7v5fqg6r9e54zq56zwcurdzzgrnfvg0l9euq2l30hf`) and post an address for me to send it back to :)

**Comment by jimmysong** [comment]
Looks pretty good! I haven't tested the psbt or address verification stuff, but I added a last word picker. Sending that PR now.

**Comment by mflaxman** [comment]
I merged all this in so we could have something live to test, but happy to make any changes. It's pretty cool!

Not sure if I'm being dumb/stubborn about putting `multiwallet.py` in the root directory (for use without needing to install), but it's pretty cool.

**Pull request merged**
